"""
Django settings for configs project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# load environment variables
load_dotenv()

from .logging import LOGGING
from .database import DATABASES
from .middlewares import MIDDLEWARE
from .jazzmin import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
for folder in ('logs', 'statics', 'medias'):
    (BASE_DIR / folder).mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
LITELLM_API_KEY = os.environ.get('LITELLM_API_KEY')

DEBUG = os.environ.get('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', os.environ.get('ALLOWED_HOST')]

# Application definition
INSTALLED_APPS = [
    # Admin
    'jazzmin',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'ninja',
    'ckeditor',
    'ckeditor_uploader',

    # Internal
    'common.apps.CommonConfig',
    'apps.posts.apps.PostConfig',
]


ROOT_URLCONF = 'configs.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ASGI_APPLICATION = 'configs.asgi.application'
WSGI_APPLICATION = 'configs.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
MEDIA_URL = 'medias/'
STATIC_URL = 'statics/'
MEDIA_ROOT = BASE_DIR / 'medias'
STATIC_ROOT = BASE_DIR / 'statics'
STATICFILES_DIRS = [BASE_DIR / 'images']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

CKEDITOR_UPLOAD_PATH = MEDIA_ROOT / "ckeditors"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 400,
        'width': '100%',
        'toolbar_Full': [
            ['Source', '-', 'Undo', 'Redo'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Iframe'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
        ],
        'extraPlugins': ['justify', 'div', 'showblocks', 'autogrow', 'codesnippet'],
        'removePlugins': ['resize'],
        'allowedContent': True,
        'toolbarCanCollapse': True,
        'autoGrow_minHeight': 400,
        'autoGrow_maxHeight': 800,
        'codeSnippet_theme': 'monokai_sublime',
    },
    'fullscreen_ckeditor': {
        'toolbar': 'AdvancedHTML',
        'height': '80vh',
        'width': '100%',
        'toolbar_AdvancedHTML': [
            ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', 'CodeSnippet', 'CodeMirror', 'Html5video', 'Html5audio', 'TableTools'],
            ['SpellChecker', 'Language'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
        ],
        'extraPlugins': [
            'justify', 'div', 'showblocks', 'autogrow', 'codesnippet', 'codemirror',
            'html5video', 'html5audio', 'maximize', 'widget', 'dialog', 'dialogui',
            'lineutils', 'clipboard', 'uploadimage', 'uploadwidget', 'image2', 'tabletools',
            'tableresize', 'table', 'embed', 'embedsemantic'
        ],
        'removePlugins': ['resize', 'image'],
        'allowedContent': True,
        'toolbarCanCollapse': True,
        'autoGrow_minHeight': 600,
        'autoGrow_maxHeight': 0,  # 0 means no max height, grows to fill screen
        'codeSnippet_theme': 'monokai_sublime',
        'codemirror': {
            'theme': 'monokai',
            'lineNumbers': True,
            'lineWrapping': True,
            'matchBrackets': True,
            'autoCloseTags': True,
            'autoCloseBrackets': True,
            'enableSearchTools': True,
            'enableCodeCompletion': True,
            'mode': 'htmlmixed',
        },
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'uploadUrl': '/ckeditor/upload/',
        'contentsCss': ['/static/css/ckeditor_custom.css'],
        'language': 'en',
        'extraAllowedContent': 'audio[*];video[*];source[*];meta[*];link[*];noscript[*];svg[*];canvas[*]',
        'protectedSource': [
            r'<script[\s\S]*?</script>',
            r'<style[\s\S]*?</style>',
            r'<code[\s\S]*?</code>',
            r'<noscript[\s\S]*?</noscript>',
            r'<meta[\s\S]*?>',
            r'<link[\s\S]*?>',
            r'<svg[\s\S]*?</svg>',
            r'<canvas[\s\S]*?</canvas>',
        ],
    },
}
