# Generated by Django 5.2.1 on 2025-05-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('blog_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the vendor or service provider', max_length=255, verbose_name='Vendor Title')),
                ('description', models.TextField(help_text='Detailed description of the services offered', verbose_name='Service Description')),
                ('price', models.CharField(help_text="Pricing information (e.g., 'Starting at $1,500', 'Packages available')", max_length=100, verbose_name='Service Price')),
                ('image_link', models.URLField(help_text="URL of the vendor's featured image or logo", max_length=512, verbose_name='Vendor Image URL')),
                ('article_link', models.URLField(help_text="Full URL to the vendor's profile page on the source website", max_length=512, unique=True, verbose_name='Vendor Profile URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when this record was first created in the system', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('posts_found', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.sourcewebsite')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.sourcewebsite')),
            ],
        ),
    ]
